### PR TITLE
Sample Data and Formal Checking

### PR DESCRIPTION
**Pull request by paulhibbing**
@bhelsel, I added a sample `gt3x` file which I think will help with some of the examples in the README and documentation.

I also ran `R CMD check` and fixed a couple things that were popping up with that (mostly related to unstated dependencies in the DESCRIPTION file).

I tried to set up automatic checking on [TRAVIS](https://travis-ci.com/), but it looks like I'm not configured properly to do this anymore. You may be in a better position to do so than I am, however. See https://docs.travis-ci.com/user/tutorial/. This is not essential, but could be nice and should hopefully take only a couple minutes to sort out.

My biggest change (which can be reversed if desired) was to change default argument settings to  `write.file = FALSE` and `return.data = TRUE`. I think this is a little more friendly since it won't modify the user's machine without asking.

### CODE REVIEW

**Comment by bhelsel** [comment]
Hi Paul, 

I'm new to the GitHub pull requests, so hopefully I didn't do anything wrong here. I think I committed all your suggestions with the exception of the automatic checking on TRAVIS. I'll need to look into that more when I have some time. I'm not sure exactly what/how to do it yet. I agree with your comment about the write.file. Most of the time, I'll be converting the files within my workflow but it makes sense that others will not want R to make changes to their computer without setting that parameter to TRUE. I also updated this in the documentation. 

Let me know if there are any other changes you see right now. I appreciate the suggestions!

Brian

**Comment by paulhibbing** [comment]
No problem Brian. I haven't done tons of pull requests, but this is intriguing. It does look like the code is merged in, but usually the PR gets marked as `merged` rather than `closed`. That may just be a formality, I don't know. [Wickham's chapter](https://r-pkgs.org/git.html#pr-accept) may be useful here as well, but all's well that ends well, regardless.

**Comment by bhelsel** [comment]
I have Hadley's book and am slowly making my way through the chapters. I'm about to start reading the testing chapter next. I also have his Advanced R book. There is some great content in that too!

The reason why it probably says closed rather than merged was because I was trying to understand the pull request process and seeing if I could add each commit individually via GitHub desktop. It sort of worked, but I'm sure I'll understand the process the more I do it. I manually closed the pull request since I added the changes a different way and it was saying that there were now conflicts. I don't know what that does for your forked repository though? I'd definitely benefit from some GitHub tutorials.

**Comment by paulhibbing** [comment]
If you're going to ICAMPAM (long shot maybe), I am giving a workshop there on git and GitHub. I think you're dead on about the value of tutorials. They'd be a big benefit to the field as a whole, and hopefully we'll get some traction in that area. Part of my motivation for engaging with this repo (apart from the fact that it's really useful -- kudos to you!) is to increase the visibility of these features and hopefully show how useful they can be.

What you described makes sense in terms of handling the PR, especially since the Travis-related commits weren't necessarily desirable. This is one of those things that can be handled in different ways. In general (so maybe not this instance specifically), I think the easiest way to handle PRs is to first have a back-and-forth in the comments about parts of the suggested code that you like and dislike. The proposer can then fix things until you're satisfied and ready to merge them. The commit history might get a little messy (in terms of undoing some things that didn't need to get done in the first place), but it might be worth it for the simplicity. Once everything is merged on GitHub, then you just need to run `git pull` in your local copy to make sure it's synced with the new changes online.

As for what happens to my forked repo, the answer should be nothing. So any changes I made should still be there, and if they differ from what you ended up incorporating, there may be conflicts. There are git-based ways for me to resolve those conflicts and get my fork synced back up, but it's possible it will just be easier for me to delete the fork and sync again. A true git user would probably roll their eyes at the last part, but there is definitely a balance when you're trying to balance the learning curve of git against the demands of actual work...

**Pull request closed without merging**
