### PR TITLE
Stopping at `last_sample_time` when present

### PR DESCRIPTION
**Pull request by paulhibbing**
I had a file for which the output of `calculate_counts` was longer than the ActiLife output. It stemmed from the `read.gt3x` output having a `last_sample_time` attribute that occurred well before the `stop_time` attribute. So the main change was to account for cases where there is a `last_sample_time` attribute followed by idle sleep mode until the end of the file. This approach is now handled via `.get_timestamps`. In my problem file, I also noticed the last row of activity count values did not match the ActiLife output. I tried to figure out how to correct that, without much success. I don't think this is a problem, just something to be aware of (which I think you have maybe documented already or discussed in an Issue).

I made some other changes along the way, which might warrant some review:

* Updated how idle sleep time is extracted, depending on whether there is a `missingness` attribute present in the input data. (I feel pretty confident in this. It may cause a bit of a slowdown in some cases and a speedup in others. But I think slowdowns should be minimal.) This is now handled via `.get_sleep`.
* Tweaked some helper functions:
  - `.resample`: Extremely minor change to avoid a redundant operation
  - `.get_frequency`: Extremely minor change to extract the value from object attributes when possible
  - `.check_idle_sleep`: Fairly substantive changes, most of which I feel good about. `zoo::na.locf0` is quite a bit faster than `zoo::na.locf`, so I think that swap will be useful. The only question mark is whether things are still handled correctly if the first observation is idle.
  - `.trim_data`: This is where I had the most questions. It looked like there was some redundant code, so I tried to sort that out. But there were also some places where I was less than 100% sure I had correctly handled the logic. I'm hopeful that it's correct (unit tests are passing, and I get equivalent output with ActiLife when testing on my problem file), but it might be worth some inspection.
* Added a dependency on `R >= 3.5.0` to pass R CMD check.

### CODE REVIEW

**Comment by paulhibbing** [comment]
Nevermind, the `get_timestamps` approach didn't fully work upon further testing. I am working to test out an approach that defines the end of the file as the last complete epoch. I'll push that if it works.

**Comment by paulhibbing** [comment]
It looks like the approach in the latest commit does a better job of outputting the correct file lengths. (This may all be related to #4 as well.)

But I'm still getting substantially different count values for *some* of my files when compared to `.agd`. I don't know what the rhyme or reason is for why this happens sometimes and not others. That said, I've toggled back and forth between the development and current versions, and I get the same results either way. So it looks like there is a separate issue somewhere, unrelated to the content of this PR.

**Comment by bhelsel** [comment]
Thanks for the pull request, Paul. Any chance you could provide sample data that could highlight the issue so I can try it both with the current agcounts version and your pull request? I want to see if I can identify what is happening before merging the pull request. Also, what is your thinking in regards to the S3 framework for extracting sleep? I was thinking S3 for reading files, but hadn't considered S3 for sleep since I was thinking a S3 for reading the data could convert it to a standard format.

**Comment by bhelsel** [comment]
@paulhibbing I was able to locate files that had a considerable difference between the output from `calculate_counts` and the ActiLife output. It seems that having a `last_sample_time` that is before the `stop_time` is common if the ActiGraph is manually stopped before it finished with the scheduled collection (e.g., calibration study) or runs out of battery (e.g., during extended field observation).

I reviewed all your changes and will merge to the development branch for now. The `trim_data` function appears to behave correctly and I verified the counts with a couple .agd files that I had with the low frequency extension option enabled. I'm still not sure about creating an S3 framework for the `.get_sleep` function as this is still something I envision with a `read` function that allows files other than ActiGraph GT3X to be read. To do this, I think we'd need to move any `read.gt3x::read.gt3x` attributes within `calculate_counts` and create a generic `read` function that includes gt3x files as a possible method. I haven't used any accelerometers other than ActiGraph yet, so this may be a development further down the road.

I'm not sure why you are getting different values for the last row, but it is something that I will look into when I have some more time. Thanks for all your contributions! When I first created this package, I followed the Python implementation as close as I could so there are probably many areas where the code can be cleaned up because of R efficiencies.

**Comment by paulhibbing** [comment]
Great, thanks Brian. Sorry for my delinquency here...

My reasoning for using S3 on `.get_sleep` was that there may be different ways of identifying/handling the sleep data, e.g. depending on the data format (data originating from `read.gt3x` versus `AGread`, `GENEAread`, etc). These varied options may have differing accuracy/efficiency, so S3 provides a way of accounting for that. Also, some monitors may handle sleep/invalid data in much different ways (i.e., totally incomparable and incompatible coding-wise), so an S3 framework makes it easy to just add a new monitor-specific method that yields the desired formatting. Even if `.get_sleep` ends up not being user-facing, this could still be valuable as an internal functionality that serves your `read` function. For example, when reading a file from one package versus another, you might want to apply a monitor-specific method for annotating sleep periods. It shouldn't cause any issues that both `read` and `.get_sleep` are S3 -- The beauty of object-oriented systems is that these kinds of relationships are easy to define, and can often be more organized/elegant than trying to take a functional approach. There are tradeoffs for sure, but this was a situation where S3 made sense to me. FWIW, I'd recommend setting up a separate package for your `read` function, as file reading tends to take on a huge scope and can have a lot of other uses as well, unrelated to calculating activity counts.

One possible reason for the differences from ActiLife is related to how `read.gt3x` imputes idle sleep data. The package always imputes zeroes but ActiLife uses a mix of  zero-imputation and last-value-carried-forward (see THLfi/read.gt3x#45).

**Comment by bhelsel** [comment]
@paulhibbing good to know about the sleep data and how it is read differently depending on the data format. I understand why you thought a S3 framework made sense. I'll need to think about a separate package for my `read` functions. I don't know that it would be worth the time since there are other good options in R now. Thanks for sending the link as I thought ActiLife only did last observation carried forward for idle sleep data. Will take a look!

**Comment by paulhibbing** [comment]
@bhelsel I get the sense that some of these issues related to latching/idle sleep mode/imputation and timestamps are present in `pygt3x` just as they were in `read.gt3x`. So, similar workarounds might be needed in order for `agcounts` to accommodate `pygt3x`. The good news is, there should be a decent chance of code being recyclable from the changes that were part of this pull request.

For context, I ran a comparison between `agread.pygt3x` and `agread.gt3x`, and I got differing file lengths along with much different count values. The pattern of differences would seem to be consistent with what we discussed before in this PR, so I think there's a good chance this is the same issue popping up for a different package.

**Pull request merged**
